---
base_apply_baseline: true
base_manage_networking: "{{ homestar_manage_static_network | default(false) | bool }}"
base_manage_firewall: true
base_manage_controller_authorized_key: true
base_manage_passwordless_sudo: true
base_passwordless_sudo_user: "{{ ansible_user }}"
base_passwordless_sudo_path: "/etc/sudoers.d/90-{{ base_passwordless_sudo_user }}"
base_visudo_path: /usr/sbin/visudo
base_controller_public_key_file: "{{ lookup('env', 'HOME') ~ '/.ssh/id_ed25519_homestar.pub' }}"
base_netplan_path: /etc/netplan/01-homestar.yaml
base_core_packages:
  - python3
  - python3-apt
  - sudo
  - chrony
  - ufw
  - curl
  - git
  - rsync
  - ca-certificates
  - gnupg
base_base_directories:
  - /srv
  - /opt/nomad
  - /etc/nomad.d
