---
homestar_node_role: nomad_server
bootstrap_final_ssh_host: 192.168.2.35
homestar_manage_static_network: true
homestar_primary_interface: enp6s0f1
homestar_ipv4_addresses:
  - 192.168.2.35/24
  - 192.168.2.202/24
homestar_service_ip: 192.168.2.35
homestar_unifi_ip: 192.168.2.202

docker_install_gcloud: true
nomad_docker_auth_config: /root/.docker/config.json

base_extra_firewall_ports:
  - { port: "8443", proto: tcp }
  - { port: "8080", proto: tcp }
  - { port: "3478", proto: udp }
  - { port: "10001", proto: udp }
  - { port: "5514", proto: udp }
  - { port: "6789", proto: tcp }
  - { port: "8843", proto: tcp }
  - { port: "8880", proto: tcp }
  - { port: "25", proto: tcp }
  - { port: "8428", proto: tcp }

nomad_host_volumes:
  - name: immich-pg-data
    path: /srv/immich-pg/data
  - name: immich-data
    path: /srv/immich/data
  - name: immich-ml-cache
    path: /srv/immich/ml-cache
  - name: unifi-config
    path: /srv/unifi/config
  - name: unifi-db
    path: /srv/unifi/db
  - name: freshrss-config
    path: /srv/freshrss/config
  - name: vaultwarden-config
    path: /srv/vaultwarden/config
  - name: linkwarden-config
    path: /srv/linkwarden/config
  - name: thelounge-config
    path: /srv/thelounge/config
  - name: duketogo-config
    path: /srv/duketogo/config
  - name: victoriametrics-data
    path: /srv/victoriametrics/data
  - name: grafana-data
    path: /srv/grafana/data
  - name: grafana-dashboards
    path: /srv/grafana/dashboards
  - name: ocis-data
    path: /srv/ocis/data
  - name: paperless-data
    path: /srv/paperless/data
  - name: paperless-media
    path: /srv/paperless/media
  - name: paperless-consume
    path: /srv/paperless/consume

caddy_routes:
  - hostname: auth.groovie.org
    backend: localhost:9000
  - hostname: photos.groovie.org
    backend: localhost:2283
  - hostname: unifi.groovie.org
    backend: https://localhost:8443
  - hostname: freshrss.groovie.org
    backend: localhost:8082
  - hostname: vaultwarden.groovie.org
    backend: localhost:8081
  - hostname: link.groovie.org
    backend: localhost:3000
  - hostname: thelounge.groovie.org
    backend: localhost:9090
  - hostname: sh.groovie.org
    backend: localhost:8888
  - hostname: paste.ofcode.org
    backend: localhost:6543
  - hostname: grafana.groovie.org
    backend: localhost:3001
  - hostname: files.groovie.org
    backend: localhost:9200
  - hostname: komga.groovie.org
    backend: 192.168.2.36:25600
  - hostname: calibre-web.groovie.org
    backend: 192.168.2.36:8083
  - hostname: music-assistant.groovie.org
    backend: 192.168.2.36:8095
  - hostname: frigate.groovie.org
    backend: 192.168.2.40:5000
  - hostname: plex.groovie.org
    backend: 192.168.2.39:32400
  - hostname: sonarr.groovie.org
    backend: 192.168.2.39:8989
  - hostname: radarr.groovie.org
    backend: 192.168.2.39:7878
  - hostname: lidarr.groovie.org
    backend: 192.168.2.39:8686
  - hostname: sabnzbd.groovie.org
    backend: 192.168.2.39:8080
  - hostname: prowlarr.groovie.org
    backend: 192.168.2.39:9696
  - hostname: paperless.groovie.org
    backend: localhost:8010

telegraf_collect_docker: true
telegraf_collect_postgres: true
telegraf_collect_nomad: true

restic_password: "{{ lookup('pipe', 'op read op://HomeCluster/restic/password') }}"
restic_s3_key: "{{ lookup('pipe', 'op read op://HomeCluster/aws/ACCESS_KEY_ID') }}"
restic_s3_secret: "{{ lookup('pipe', 'op read op://HomeCluster/aws/SECRET_ACCESS_KEY') }}"
