[nomad_server]
epyc ansible_host=192.168.2.35

[nomad_client]
h4uno ansible_host=192.168.2.36
h4dos ansible_host=192.168.2.39
beelink1 ansible_host=192.168.2.40

[postgres]
epyc

[nodes:children]
nomad_server
nomad_client

[nodes:vars]
ansible_user=ansible
ansible_become=true
