---
- name: Apply the homestar baseline
  hosts: all
  gather_facts: true
  become: true
  tags: [base]
  roles:
    - role: base

- name: Install and configure Docker
  hosts: all
  gather_facts: true
  become: true
  tags: [docker]
  roles:
    - role: docker

- name: Install and configure 1Password CLI
  hosts: epyc
  gather_facts: true
  become: true
  tags: [onepassword]
  roles:
    - role: onepassword

- name: Install and configure Nomad
  hosts: nomad_server:nomad_client
  gather_facts: true
  become: true
  tags: [nomad]
  roles:
    - role: nomad

- name: Install and configure PostgreSQL
  hosts: postgres
  gather_facts: true
  become: true
  tags: [postgres]
  roles:
    - role: postgres

- name: Install and configure Caddy
  hosts: epyc
  gather_facts: true
  become: true
  tags: [caddy]
  roles:
    - role: caddy

- name: Configure Cloudflare DNS records
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tags: [cloudflare-dns]
  roles:
    - role: cloudflare-dns

- name: Configure opnSense DNS host overrides
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tags: [opnsense-dns]
  roles:
    - role: opnsense-dns
